use_frameworks!

platform :ios, '9.0'

target 'LSTCategorySwift_Example' do
  pod 'LSTCategorySwift', :path => '../'

  target 'LSTCategorySwift_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
